server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ivrengine?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: 12qwaszx
    platform: postgres
    driver-class-name: org.postgresql.Driver
  session:
    store-type: none
  servlet:
    multipart:
      enabled: true
      location: temp123
      file-size-threshold: 5MB
      max-file-size: 10MB
      max-request-size: 20MB
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
file:
  storage:
    location: fileStorage

